-- ============================================================================
-- APPLICATION MANAGEMENT MODULE
-- Production-grade schema for job applications and tracking
-- ============================================================================

-- Applications table - main job applications
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique application identifier',
    job_id BIGINT NOT NULL COMMENT 'Reference to jobs table',
    candidate_id BIGINT NOT NULL COMMENT 'Reference to candidates table',
    applied_resume_id BIGINT COMMENT 'Reference to candidate_resumes table',
    application_text TEXT COMMENT 'Application cover letter/text',
    application_status ENUM('APPLIED', 'REVIEWED', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'ACCEPTED') DEFAULT 'APPLIED' COMMENT 'Application status',
    rejection_reason VARCHAR(500) COMMENT 'Reason for rejection',
    rejection_notes TEXT COMMENT 'Detailed rejection notes',
    rejected_at TIMESTAMP NULL COMMENT 'When application was rejected',
    rejected_by BIGINT COMMENT 'User ID who rejected',
    is_read BOOLEAN DEFAULT FALSE COMMENT 'Application read status',
    is_flagged BOOLEAN DEFAULT FALSE COMMENT 'Flagged for follow-up',
    flag_reason VARCHAR(255) COMMENT 'Reason for flag',
    interview_count INT DEFAULT 0 COMMENT 'Number of interviews',
    rating INT COMMENT 'Application rating (1-5)',
    rating_notes TEXT COMMENT 'Rating notes',
    rated_by BIGINT COMMENT 'User ID who rated',
    rated_at TIMESTAMP NULL COMMENT 'When rated',
    match_score DECIMAL(5, 2) COMMENT 'Skill match score (0-100)',
    match_details JSON COMMENT 'Match score details',
    source ENUM('DIRECT_APPLICATION', 'RECRUITER_INVITE', 'BULK_INVITE', 'REFERRAL', 'EXTERNAL') DEFAULT 'DIRECT_APPLICATION' COMMENT 'Application source',
    referred_by BIGINT COMMENT 'Referrer user ID',
    external_reference_id VARCHAR(100) COMMENT 'External system reference',
    priority_level ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') DEFAULT 'MEDIUM' COMMENT 'Application priority',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (applied_resume_id) REFERENCES candidate_resumes(id) ON DELETE SET NULL,
    FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (rated_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (referred_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY uk_job_candidate (job_id, candidate_id),
    INDEX idx_job_id (job_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_application_status (application_status),
    INDEX idx_is_read (is_read),
    INDEX idx_is_flagged (is_flagged),
    INDEX idx_match_score (match_score),
    INDEX idx_priority_level (priority_level),
    INDEX idx_source (source),
    INDEX idx_created_at (created_at),
    INDEX idx_updated_at (updated_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Job applications';

-- Saved Jobs table - candidates saving jobs
CREATE TABLE IF NOT EXISTS saved_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique saved job identifier',
    job_id BIGINT NOT NULL COMMENT 'Reference to jobs table',
    candidate_id BIGINT NOT NULL COMMENT 'Reference to candidates table',
    saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When job was saved',
    notes TEXT COMMENT 'Candidate notes about job',
    reminder_at TIMESTAMP NULL COMMENT 'Reminder timestamp',
    reminder_sent BOOLEAN DEFAULT FALSE COMMENT 'Reminder sent flag',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    UNIQUE KEY uk_candidate_job (candidate_id, job_id),
    INDEX idx_job_id (job_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_saved_at (saved_at),
    INDEX idx_reminder_at (reminder_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Candidates saved jobs';

-- Shortlisted Candidates table
CREATE TABLE IF NOT EXISTS shortlisted_candidates (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique shortlist identifier',
    application_id BIGINT NOT NULL COMMENT 'Reference to applications table',
    job_id BIGINT NOT NULL COMMENT 'Reference to jobs table',
    candidate_id BIGINT NOT NULL COMMENT 'Reference to candidates table',
    shortlist_stage INT DEFAULT 1 COMMENT 'Shortlist stage number',
    shortlisted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When shortlisted',
    shortlisted_by BIGINT NOT NULL COMMENT 'User ID who shortlisted',
    shortlist_notes TEXT COMMENT 'Shortlist notes',
    expected_feedback_date DATE COMMENT 'Expected feedback date',
    feedback_received BOOLEAN DEFAULT FALSE COMMENT 'Feedback received flag',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (shortlisted_by) REFERENCES users(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_application_stage (application_id, shortlist_stage),
    INDEX idx_job_id (job_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_shortlist_stage (shortlist_stage),
    INDEX idx_shortlisted_at (shortlisted_at),
    INDEX idx_feedback_received (feedback_received),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Shortlisted candidates';

-- Interview Schedules table
CREATE TABLE IF NOT EXISTS interview_schedules (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique interview identifier',
    application_id BIGINT NOT NULL COMMENT 'Reference to applications table',
    job_id BIGINT NOT NULL COMMENT 'Reference to jobs table',
    candidate_id BIGINT NOT NULL COMMENT 'Reference to candidates table',
    interview_type ENUM('PHONE', 'VIDEO', 'IN_PERSON', 'PRACTICAL', 'GROUP', 'FINAL') DEFAULT 'VIDEO' COMMENT 'Type of interview',
    interview_round INT NOT NULL COMMENT 'Interview round number',
    scheduled_at TIMESTAMP NOT NULL COMMENT 'Scheduled interview time',
    duration_minutes INT DEFAULT 30 COMMENT 'Interview duration in minutes',
    scheduled_by BIGINT NOT NULL COMMENT 'User ID who scheduled',
    interviewer_id BIGINT COMMENT 'Primary interviewer user ID',
    interviewer_ids JSON COMMENT 'JSON array of interviewer user IDs',
    meeting_url VARCHAR(500) COMMENT 'Meeting URL (Zoom, Teams, etc)',
    meeting_provider VARCHAR(100) COMMENT 'Meeting provider (ZOOM, TEAMS, MEET)',
    meeting_id VARCHAR(100) COMMENT 'Meeting ID in provider',
    interview_location VARCHAR(255) COMMENT 'Location for in-person interviews',
    additional_instructions TEXT COMMENT 'Instructions for candidate',
    confirmation_sent BOOLEAN DEFAULT FALSE COMMENT 'Confirmation sent flag',
    confirmation_sent_at TIMESTAMP NULL COMMENT 'When confirmation was sent',
    is_confirmed BOOLEAN DEFAULT FALSE COMMENT 'Candidate confirmation flag',
    confirmed_at TIMESTAMP NULL COMMENT 'When candidate confirmed',
    candidate_attended BOOLEAN DEFAULT FALSE COMMENT 'Candidate attended flag',
    started_at TIMESTAMP NULL COMMENT 'When interview started',
    ended_at TIMESTAMP NULL COMMENT 'When interview ended',
    is_cancelled BOOLEAN DEFAULT FALSE COMMENT 'Interview cancelled flag',
    cancelled_at TIMESTAMP NULL COMMENT 'When cancelled',
    cancellation_reason VARCHAR(500) COMMENT 'Cancellation reason',
    cancelled_by BIGINT COMMENT 'User ID who cancelled',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (scheduled_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (interviewer_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_application_id (application_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_scheduled_at (scheduled_at),
    INDEX idx_interview_type (interview_type),
    INDEX idx_interview_round (interview_round),
    INDEX idx_is_confirmed (is_confirmed),
    INDEX idx_candidate_attended (candidate_attended),
    INDEX idx_is_cancelled (is_cancelled),
    INDEX idx_created_at (created_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Interview scheduling';

-- Interview Feedback table
CREATE TABLE IF NOT EXISTS interview_feedback (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique feedback identifier',
    interview_id BIGINT NOT NULL UNIQUE COMMENT 'Reference to interview_schedules table',
    application_id BIGINT NOT NULL COMMENT 'Reference to applications table',
    candidate_id BIGINT NOT NULL COMMENT 'Reference to candidates table',
    interviewer_id BIGINT NOT NULL COMMENT 'Interviewer user ID',
    overall_rating INT NOT NULL COMMENT 'Overall rating (1-10)',
    technical_rating INT COMMENT 'Technical rating (1-10)',
    communication_rating INT COMMENT 'Communication rating (1-10)',
    cultural_fit_rating INT COMMENT 'Cultural fit rating (1-10)',
    strengths TEXT COMMENT 'Candidate strengths',
    weaknesses TEXT COMMENT 'Areas for improvement',
    interview_feedback TEXT NOT NULL COMMENT 'Detailed feedback',
    recommendation ENUM('STRONG_YES', 'YES', 'MAYBE', 'NO', 'STRONG_NO') DEFAULT 'MAYBE' COMMENT 'Interview recommendation',
    next_steps TEXT COMMENT 'Next steps',
    follow_up_date DATE COMMENT 'Follow-up date',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    
    FOREIGN KEY (interview_id) REFERENCES interview_schedules(id) ON DELETE CASCADE,
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (interviewer_id) REFERENCES users(id) ON DELETE RESTRICT,
    INDEX idx_application_id (application_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_interviewer_id (interviewer_id),
    INDEX idx_overall_rating (overall_rating),
    INDEX idx_recommendation (recommendation),
    INDEX idx_created_at (created_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Interview feedback and ratings';

-- Application History table - audit trail
CREATE TABLE IF NOT EXISTS application_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique history record identifier',
    application_id BIGINT NOT NULL COMMENT 'Reference to applications table',
    changed_by BIGINT NOT NULL COMMENT 'User ID who made change',
    old_status VARCHAR(50) COMMENT 'Previous status',
    new_status VARCHAR(50) COMMENT 'New status',
    change_reason VARCHAR(500) COMMENT 'Reason for change',
    change_details JSON COMMENT 'JSON details of changes',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE RESTRICT,
    INDEX idx_application_id (application_id),
    INDEX idx_changed_by (changed_by),
    INDEX idx_new_status (new_status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Application status history and audit trail';
